name: Python Lint and Test

on:
  push:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1

    - name: Set up Python 3.8
      uses: actions/setup-python@v1
      with:
        python-version: 3.8

    - name: Install dependencies
      run: |
        make install-dev

    - name: Run pre-commit hooks
      run: |
        make lint

    - name: Run unit tests
      run: |
        make test
